# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AU1I8qtimVU_6g_q-_j6AYWNxsyKfnzL
"""

estados = input().split(" ")
simbolo_alfabeto = input().split(" ")
qtd_transicoes = int(input())

trans_afd = {}

for estado in estados:
    trans_afd[estado] = {}

for i in range(0, qtd_transicoes):
    inicio, caractere, final = input().split(" ")
    if caractere not in trans_afd[inicio]:
      trans_afd[inicio][caractere] = final

estado_inicial = input()
estados_finais = input().split(" ")
palavras = input().split(" ")

for palavra in palavras:
    estado_atual = estado_inicial
    estado_de_error = 0
    for char in palavra:
        try:
            estado_atual = trans_afd[estado_atual][char]
        except KeyError:
            estado_de_error = 1
            break
    if(estado_de_error == 1 or estado_atual not in estados_finais):
        print('N')
    else:
        print('S')